### PR TITLE
Firebase Hosting fix

### PR DESCRIPTION
**Pull request by charitarthchugh**
- Deploy using firebase
- Delete deploy.yml
- Fix Hosting issues on Firebase

### CODE REVIEW

**Comment by charitarthchugh** [comment]
@m4nik1 please help me fix this?

**Review by uconn-ai — APPROVED** [review]

**Comment by m4nik1** [comment]
Could not go the preview that the github action gave. Please fix this. @charitarthchugh

**Comment by m4nik1** [comment]
Fine, will deploy.

**Review by m4nik1 — APPROVED** [review]
looks good. Ship it!

**Pull request merged**
